<#
    YanZhen - store promo tile generator
    ====================================
    Generates the two optional promo tiles the Edge Add-ons listing accepts:
      · small promo tile  440 x 280
      · large promo tile 1400 x 560

    Reads the icon from store\assets\logo-512.png (generated by gen_icons.py).

    NOTE: this file contains Chinese text and is executed via
    `powershell -File`, so it MUST be saved as UTF-8 **with BOM**.
    (A BOM-less .ps1 gets read as GBK and the Chinese turns into garbage.)
    store\gen_promo_bom.py re-adds the BOM if an editor strips it.

    Usage:
      powershell -ExecutionPolicy Bypass -File store\gen_promo.ps1
#>
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Split-Path -Parent $here
$iconPath = Join-Path $here 'assets\logo-512.png'
$outDir = Join-Path $here 'assets'

if (-not (Test-Path $iconPath)) { throw "icon not found: $iconPath (run store\gen_icons.py first)" }

$BG      = [System.Drawing.Color]::FromArgb(17, 24, 39)      # #111827
$WHITE   = [System.Drawing.Color]::FromArgb(255, 255, 255)
$GRAY    = [System.Drawing.Color]::FromArgb(209, 213, 219)   # #d1d5db
$GRAY2   = [System.Drawing.Color]::FromArgb(156, 163, 175)   # #9ca3af
$GRAY3   = [System.Drawing.Color]::FromArgb(107, 114, 128)   # #6b7280

function New-Tile {
    param(
        [int]$W, [int]$H, [string]$Out,
        [int]$IconX, [int]$IconY, [int]$IconSize,
        [int]$TextX,
        [string]$TitleText, [float]$TitleY, [float]$TitleSize,
        [string]$SubText,   [float]$SubY,   [float]$SubSize,
        [string]$TagText,   [float]$TagY,   [float]$TagSize,
        [float]$FootSize
    )

    $bmp = New-Object System.Drawing.Bitmap $W, $H
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::ClearTypeGridFit
    $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $g.Clear($BG)

    # 图标
    $icon = [System.Drawing.Image]::FromFile($iconPath)
    $g.DrawImage($icon, (New-Object System.Drawing.Rectangle $IconX, $IconY, $IconSize, $IconSize))
    $icon.Dispose()

    # 可用宽度：从 TextX 到右边缘留 28px 边距
    $avail = $W - $TextX - 28

    # 自动缩字号：实测宽度，超了就等比缩小 —— 从根上保证不截断
    function Fit($text, $size, $bold) {
        if (-not $text) { return @{ Font = (New-Object System.Drawing.Font 'Microsoft YaHei', $size); Shrunk = $false } }
        $style = if ($bold) { [System.Drawing.FontStyle]::Bold } else { [System.Drawing.FontStyle]::Regular }
        $f = New-Object System.Drawing.Font 'Microsoft YaHei', $size, $style
        $sz = $g.MeasureString($text, $f)
        $try = 0
        while ($sz.Width -gt $avail -and $size -gt 6 -and $try -lt 40) {
            $f.Dispose()
            $size = $size * 0.94
            $f = New-Object System.Drawing.Font 'Microsoft YaHei', $size, $style
            $sz = $g.MeasureString($text, $f)
            $try++
        }
        return @{ Font = $f; Shrunk = ($try -gt 0) }
    }

    $ft = Fit $TitleText $TitleSize $true
    $fs = Fit $SubText   $SubSize   $false
    $fg = Fit $TagText   $TagSize   $false

    $bWhite = New-Object System.Drawing.SolidBrush $WHITE
    $bGray2 = New-Object System.Drawing.SolidBrush $GRAY2
    $bGray3 = New-Object System.Drawing.SolidBrush $GRAY3

    $g.DrawString($TitleText, $ft.Font, $bWhite, $TextX, $TitleY)
    if ($SubText) { $g.DrawString($SubText, $fs.Font, $bGray2, $TextX, $SubY) }
    if ($TagText) { $g.DrawString($TagText, $fg.Font, $bGray3, $TextX, $TagY) }

    $fFoot = New-Object System.Drawing.Font 'Consolas', $FootSize
    $g.DrawString('github.com/Ariscty/yanzhen', $fFoot, $bGray3, $TextX, ($H - $FootSize * 2.4))
    $g.Dispose()

    $path = Join-Path $outDir $Out
    $bmp.Save($path, [System.Drawing.Imaging.ImageFormat]::Png)
    $bmp.Dispose()
    foreach ($f in @($ft.Font, $fs.Font, $fg.Font, $fFoot)) { $f.Dispose() }
    foreach ($b in @($bWhite, $bGray2, $bGray3)) { $b.Dispose() }

    $fitNote = if ($ft.Shrunk -or $fs.Shrunk -or $fg.Shrunk) { ' (auto-shrunk to fit)' } else { '' }
    Write-Host ("  {0}  {1} x {2}  {3:N0} bytes   title {4}px / sub {5}px / tag {6}px{7}" -f `
        $Out, $W, $H, (Get-Item $path).Length,
        [int]$ft.Font.Size, [int]$fs.Font.Size, [int]$fg.Font.Size, $fitNote)
}

Write-Host 'generating promo tiles:'
# 小磁贴 440x280 —— 文字必须短
New-Tile -W 440 -H 280 -Out 'promo-440x280.png' `
    -IconX 26 -IconY 62 -IconSize 156 -TextX 206 `
    -TitleText '验真' -TitleY 66 -TitleSize 46 `
    -SubText '划词事实核查' -SubY 148 -SubSize 16 `
    -TagText '结论 + 证据来源' -TagY 180 -TagSize 13 `
    -FootSize 12

# 大磁贴 1400x560
New-Tile -W 1400 -H 560 -Out 'promo-1400x560.png' `
    -IconX 80 -IconY 130 -IconSize 300 -TextX 448 `
    -TitleText '验真' -TitleY 122 -TitleSize 96 `
    -SubText '划词事实核查 · 选中文字，按快捷键' -SubY 280 -SubSize 34 `
    -TagText '结论 + 证据来源，查不到就直说' -TagY 348 -TagSize 26 `
    -FootSize 22

Write-Host 'done -> store\assets\'
